Framework=Playwright
Language=TypeScript
Environment=staging
BaseURL=https://www.saucedemo.com
ApiURL=https://reqres.in/api
Browser=Chromium (Mobile Emulation)
Devices=iPhone 14, Pixel 7, iPad Pro 11
OS=Linux
NodeVersion=18+
